### ISSUE TITLE
cannot repo init on ubuntu16.04 with python TypeError

### ISSUE THREAD

**Issue by fengyingchu0827** [intel/iotg-yocto-ese-manifest#2]
Hi,
My environment is Ubuntu 16.04. I got "TypeError: __init__() got an unexpected keyword argument encoding" when I used repo init.
Could you please check it for me? Thanks a lot.

The following shows the log I got:

fengying_chu@fengyingchu-TS700-E6-RS8:~/workspace/tsn/new-release-51$ repo init -u git@github.com:intel/iotg-yocto-ese-manifest.git -b refs/heads/master -g all
Downloading Repo source from https://gerrit.googlesource.com/git-repo
remote: Counting objects: 16, done
remote: Finding sources: 100% (101/101)
remote: Total 101 (delta 44), reused 101 (delta 44)
Receiving objects: 100% (101/101), 97.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (44/44), completed with 12 local objects.
repo: warning: Invalid UTF-8 output:
cmd: ['git', 'tag', '-v', 'v2.13.4']
b'gpg: Signature made \xe5\xbb\xbf\xe5\xbb\xbf\xe4\xb8\x80\xe5\xb9\xb4\xe4\xb8\x89\xe6\x9c\x88\xe5\x8d\x81\xe6\x97\xa5 (\xe9\x80\xb1\xe4\xb8\x89) \xe4\xba\x8c\xe6\x99\x82\xe5\xbb\xbf\xe4\xba\x8c\xe5\x88 using DSA key ID 920F5C65\ngpg: Good signature from "Repo Maintainer <repo@android.kernel.org>"\ngpg: WARNING: This key is not certified with a trusted signature!\ngpg:          There is no indication that the signature belongs to the owner.\nPrimary key fingerprint: 8BB9 AD79 3E8E 6153 AF0F  9A44 1653 0D5E 920F 5C65\n'
repo: warning: your Python 3 version is no longer supported; Please upgrade to Python 3.6+.

... A new version of repo (2.12) is available.
... You should upgrade soon:
    cp /home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/repo /home/fengying_chu/bin/repo

Traceback (most recent call last):
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/main.py", line 629, in <module>
    _Main(sys.argv[1:])
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/main.py", line 603, in _Main
    result = run()
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/main.py", line 596, in <lambda>
    run = lambda: repo._Run(name, gopts, argv) or 0
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/main.py", line 205, in _Run
    git_trace2_event_log = EventLog()
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/git_trace2_event_log.py", line 86, in __init__
    self._AddVersionEvent()
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/git_trace2_event_log.py", line 96, in _AddVersionEvent
    version_event['exe'] = RepoSourceVersion()
  File "/home/fengying_chu/workspace/tsn/new-release-51/.repo/repo/git_command.py", line 166, in RepoSourceVersion
    encoding='utf-8', env=env, check=False)
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'encoding'
fengying_chu@fengyingchu-TS700-E6-RS8:~/workspace/tsn/new-release-51$

**Comment by jyong2** [comment]
Repo tools did a self-update and now requires python3.6 or later installed. Looks like it is only available on Ubuntu 18.04 or later:
https://packages.ubuntu.com/search?keywords=python3

**Comment by fengyingchu0827** [comment]
It works on ubuntu 18.04. Thanks.
